### ISSUE TITLE
数据库初始化失败

### ISSUE THREAD

**Issue by china-bigcloud** [unixhot/opsany-paas#1]
![image](https://user-images.githubusercontent.com/25924469/169936234-0de838d9-7df6-468a-b11c-993f8c133792.png)
![image](https://user-images.githubusercontent.com/25924469/169936172-0c863cd4-dc0c-4d77-bedf-cf102bccc536.png)

**Comment by unixhot** [comment]
可以卸载重新安装，检查下Selinux，磁盘权限之类。
