### ISSUE TITLE
Zabbix Sehell Script Error

### ISSUE THREAD

**Issue by dinghui40** [unixhot/opsany-paas#4]
### **BUG反馈(This a BUG REPORT)** :

1. **PaaS/PaaSAgent版本(The versions used):**
    v2.2.0

3. **发生了什么(What happened):**
    在我使用 [官方文档](https://docs.opsany.com/deploy/monitor-install/) 部署 Zabbix 监控后, 我想卸载并重新安装, 使用卸载时脚本出现报错函数不存在
   I tried to uninstall after deployment, but the script reported an error indicating that the parameter did not exist

    函数为: zabbix_uninstall
    The parameter is: zabbix_uninstall

4. **期望是什么(What you expected to happen):**
    我希望合并新的提交: https://github.com/unixhot/opsany-paas/pull/3
    I want to merge new submissions: https://github.com/unixhot/opsany-paas/pull/3

5. **如何复现(How to reproduce it):**
    在安装 Zabbix 后执行 `./zabbix-install.sh uninstall6` 或 `./zabbix-install.sh uninstall5` 即可复现
    After installing zabbix, run './zabbix-install.sh uninstall6 'or'./zabbix-install.sh uninstall5 '

7. **相关的日志详情:**
    <img width="694" alt="image" src="https://github.com/unixhot/opsany-paas/assets/102201557/6d08e9bc-0ef7-4bac-b7f2-dbe178144f80">

8. **备注(Anything else we need to know):** 
    该提交已经过验证可用, 结果如下
    The submission has been verified as usable with the following results
    5.0:
    <img width="1020" alt="image" src="https://github.com/unixhot/opsany-paas/assets/102201557/f77a5b9c-bf61-4fb9-9895-de9782b2739d">
    6.0:
    <img width="1010" alt="image" src="https://github.com/unixhot/opsany-paas/assets/102201557/42d6c85a-8e40-471a-ab29-50ff8acba726">

**Comment by unixhot** [comment]
感谢建议，已经修改完毕。
