### ISSUE TITLE
如果所有容器都删除了之后如何启动，或者如何重启，在最新的版本中找不到重启脚本了？

### ISSUE THREAD

**Issue by abelit** [unixhot/opsany-paas#5]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

**PaaS/PaaSAgent版本(The versions used):**

**发生了什么(What happened):**

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by unixhot** [comment]
新版本已经不需要重启脚本，直接docker restart xxx，重启某个容器即可。
